language: node_js
node_js:
  - '14'
services:
  - docker
cache: npm
branches:
  only:
    - main
env:
  global:
    - APP_PORT=4376
    - DB_URI=$DB_URI
    - JWT_SECRET=$JWT_SECRET
script:
  - npm run test
  - npm run test:e2e
after_success: npm run coverage:coveralls
